add_newline = false

# Full CLI format
format = """
$time\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$kubernetes\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$buf\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""


[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✘](bold red)"

[directory]
truncation_length = 8
truncation_symbol = "../"
truncate_to_repo = true
style = "white bold"

[hostname]
ssh_only = true
format = "[$hostname]($style):"

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
style = 'green underline'

[memory_usage]
disabled = false

[time]
disabled = false
format = "\\[[$time]($style)\\] "
time_format = "%T"